---
- name: Install OpenSSH server
  apt:
    name: "{{ openssh_server_pkg_name }}"
    state: "{{ openssh_server_pkg_state }}"


- name: Install OpenSSH client
  apt:
    name: "{{ openssh_client_pkg_name }}"
    state: "{{ openssh_client_pkg_state }}"
